### PR TITLE
docs: Removed SECURITY.md

### PR DESCRIPTION
**Pull request by vaughnw128**
This PR is to remove the SECURITY.md file from the repository, as SECURITY.md files are centrally managed in the organization's [.github](https://github.com/newrelic/.github) repository. This allows for easy updates made by security in the future.

### CODE REVIEW

**Review by jsumners-nr — CHANGES_REQUESTED** [review]
Please update references: https://github.com/newrelic/newrelic-node-versions/blob/f5dd32672ddb2faad7fab3ea899275b5577991b9/Readme.md?plain=1#L95

**Comment by vaughnw128** [comment]
Hi @jsumners-nr, I've updated the reference to link to the security policy tab in the repository. Once the PR is merged that security policy page will be replaced with the SECURITY.md located in .github. Thanks!

**Review by jsumners-nr — APPROVED** [review]

**Comment by bizob2828** [comment]
This repo was created from a template. Was that updated to avoid this in the future?

**Comment by vaughnw128** [comment]
@bizob2828 It doesn't look like the template has a SECURITY.md present, so it should be alright: https://github.com/newrelic/newrelic-repo-template

An issue could arise if devs add the SECURITY.md themselves, but I think with Github making the security policy more visible in the README section that's unlikely. One less file in the root level of the repo!

**Comment by bizob2828** [comment]
ok yea i see the template has the right link. We've also had a violation https://github.com/newrelic/newrelic-node-versions/issues/25 which I'll close

**Comment by bizob2828** [comment]
Something is up with repolinter https://github.com/newrelic/newrelic-node-versions/issues/39

**Comment by vaughnw128** [comment]
> Something is up with repolinter #39

It looks like there's an issue with the repolinter's match on finding the security policy. It's looking for newrelic-experimental

https://github.com/newrelic/.github/blob/main/repolinter-rulesets/new-relic-experimental.yml#L82

**Comment by bizob2828** [comment]
it expected URL to be in the `newrelic-experimental` org `https:\/\/github\.com\/newrelic-experimental\/[^\/]+)|(?:\.\.\/\.\.))\/security\/policy`

**Comment by vaughnw128** [comment]
> it expected URL to be in the `newrelic-experimental` org `https:\/\/github\.com\/newrelic-experimental\/[^\/]+)|(?:\.\.\/\.\.))\/security\/policy`

I think this is due to the fact that this repo is considered 'experimental.' The problem is that we can't change the underlying repolinter ruleset as it's being referenced in every single `newrelic-experimental` repository. We may want to create a repolinter ruleset that is specific to experimental repos in the `newrelic` organization.

**Comment by bizob2828** [comment]
I just moved to community project. we do maintain this. it's used internally and I don't feel like moving to the experimental org

**Comment by vaughnw128** [comment]
Yeah, moving to experimental would be a bit of a waste of time. Thanks for fixing that up!

**Comment by mrickard** [comment]
@vaughnw128 It looks like repolinter is still having some problems in #41 . Would that require a change here or in repolinter?

**Pull request merged**
